name: Anonymize database and export it
on:
  pull_request:
    branches: [ main ]
jobs:
  anonymize:
    runs-on: ubuntu-latest
    steps:
      - name: Anonymize Data
        uses: pvcy/anonymize-project@latest
        with:
          project-id: 4e1213f4-my-project-uuid-0242ac120002
          db-host: my_postgres_host.host.com
          db-port: 5432
          db-username: ${{ secrets.PG_USERNAME }}
          db-password: ${{ secrets.PG_PASSWORD }}
          client-id: ${{ secrets.DB_SSH_KEY }}
          client-secret: ${{ secrets.DB_SSH_SECRET }}
  dump-database:
    runs-on: ubuntu-latest
    steps:
    - name: Dump database to blob storage
      run: |
        some bash command to call pgdump