name: Backup database to blob cloud storage
on:
  pull_request:
    branches: [ develop ]
# on:
#   schedule: 
#     - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: database-migration-anonymized
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Backup database
      run: |
        pg_dump -h db \
          -U postgres \
          -d postgres \
          -F t \
          -f db_backup.tar

    - name: Copy backup to storage
      run: |
        gsutil cp db_backup.tar gs://anonymize-db-backups/us-west1/




