name: Deploy app to Cloud Run
on:
  pull_request:
    branches: [ main ]
# on:
#   schedule: 
#     - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: database-migration-anonymized
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push database image
      run: |
        cd ./db
        docker build -t destination-db .
        gcloud auth configure-docker
        docker tag destination-db:latest gcr.io/database-migration-anonymized/destination-db
        docker push gcr.io/database-migration-anonymized/destination-db

    - name: Deploy to Cloud Run # service must already exist
      run: |
        gcloud run deploy destination-database \
          --image=gcr.io/database-migration-anonymized/destination-db \
          --platform managed \
          --allow-unauthenticated \
          --region us-west1

    - name: Backup database
      run: |
        pg_dump -h db \
          -U postgres \
          -d postgres \
          -F t \
          -f db_backup.tar

    - name: Copy backup to storage
      run: |
        gsutil cp db_backup.tar gs://anonymize-db-backups




