name: Create Preview and Test Migration
on:
  pull_request:
    branches: [ main ]
    paths: 
    - 'users-api/src/migrations/**'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: okteto/context@2.19.2
        with:
          token: ${{ secrets.OKTETO_GCP_TOKEN }}
          url: ${{ secrets.OKTETO_GCP_URL }}

      - name: Deploy preview environment
        uses: okteto/deploy-preview@2.19.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: anonymize-pr-${{ github.event.number }}
          scope: global
          timeout: 15m

  load-data:
    name: Load data from snapshot
    runs-on: ubuntu-latest
    steps:
      - id: load-data-from-snapshot
        run: |
          echo "some bash command goes here"

  tests:
    name: Verify migration works
    runs-on: ubuntu-latest
    needs: preview
    steps:
      - id: run-migration
        name: Run Sequelize migration
        run: npx sequelize-cli db:migrate
